spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '1234'

elastic-query-web-client:
  webclient:
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
