spring:
  application:
    name: reactive-elastic-query-web-client
  profiles:
    active: reactive_elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: reactive-elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '1234'
