server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafaelpadu/config-server-repository
          default-label: master
          username: rafaelpadu
          password: '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'
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '1234'

log:
  app-name: config-server
